In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
import numpy as np
import warnings

warnings.filterwarnings('ignore')

In [4]:
df=pd.read_csv('car sales dataset.csv')
df

,Car Model,Country,City,Price,QuantitySold,Sale,DateOfSale,CustomerID,CustomerName,Age,Gender,CarMake,CarModel,Year,CarType,PaymentMethod,SalespersonID,SalespersonName,DealershipLocation,Profit
0,Hyundai Elantra,USA,Phoenix,58969,9,530721,19-10-2024,CUST00001,David Newton,24,Male,Mercedes,Mercedes C-Class,2022,SUV,Cash,SP050,Daisy Becker,"Lisaside, Palestinian Territory",7504
1,Honda Civic,Australia,Melbourne,82809,2,165618,20-10-2024,CUST00002,Mark Haas,25,Non-binary,Nissan,Ford Focus,2019,Convertible,Credit Card,SP027,Kelly Smith,"South Amber, Reunion",14973
2,Hyundai Elantra,Australia,Adelaide,54925,10,549250,21-10-2024,CUST00003,Emily Brooks,33,Male,Toyota,Kia Optima,2007,Truck,Lease,SP071,Christian Morgan,"Kristinmouth, Cuba",7008
3,BMW 3 Series,Canada,Toronto,34601,10,346010,22-10-2024,CUST00004,Samantha Fernandez,21,Non-binary,Toyota,Mercedes C-Class,2016,SUV,Credit Card,SP055,George Santiago,"Patrickmouth, French Guiana",11729
4,BMW 3 Series,France,Nice,49742,1,49742,23-10-2024,CUST00005,Linda Wilson,42,Female,BMW,BMW 3 Series,2002,Minivan,Bank Transfer,SP007,Brittany Brown,"Reneeborough, Kyrgyz Republic",6025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Nissan Altima,India,Hyderabad,29989,8,239912,01-03-2052,CUST09996,John Adkins,51,Female,BMW,Ford Focus,2006,Truck,Credit Card,SP053,Ian Miller,"North Kim, Netherlands",5423
9996,Nissan Altima,Germany,Berlin,19653,10,196530,02-03-2052,CUST09997,Monica Gonzales,29,Non-binary,Audi,Honda Civic,2004,Convertible,Cash,SP057,Michelle Foster,"West Jasmine, Kyrgyz Republic",3515
9997,Ford Focus,France,Nice,78831,3,236493,03-03-2052,CUST09998,Shane Gill,33,Non-binary,Audi,Nissan Altima,2001,SUV,Cash,SP089,Ian Rodriguez,"Hernandezmouth, Costa Rica",12366
9998,BMW 3 Series,China,Shanghai,50372,5,251860,04-03-2052,CUST09999,Derek Smith,31,Male,BMW,Chevrolet Malibu,2003,Hatchback,Credit Card,SP027,Kathy Gonzalez,"Diazmouth, New Zealand",13982
9999,Honda Civic,China,Shenzhen,19471,2,38942,05-03-2052,CUST10000,Ronald Garcia,64,Female,Audi,BMW 3 Series,2022,Convertible,Lease,SP039,Laura Stokes,"South Katelyn, Mozambique",7396

In [5]:
df.isnull().sum()

Car Model             0
Country               0
City                  0
Price                 0
QuantitySold          0
Sale                  0
DateOfSale            0
CustomerID            0
CustomerName          0
Age                   0
Gender                0
CarMake               0
CarModel              0
Year                  0
CarType               0
PaymentMethod         0
SalespersonID         0
SalespersonName       0
DealershipLocation    0
Profit                0
dtype: int64

In [6]:
!pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in c:\users\dell\anaconda3\lib\site-packages (1.1.2)
Requirement already satisfied: sqlalchemy in c:\users\dell\anaconda3\lib\site-packages (2.0.34)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\dell\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\dell\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)

In [7]:
df.columns

Index(['Car Model', 'Country', 'City', 'Price', 'QuantitySold', 'Sale',
       'DateOfSale', 'CustomerID', 'CustomerName', 'Age', 'Gender', 'CarMake',
       'CarModel', 'Year', 'CarType', 'PaymentMethod', 'SalespersonID',
       'SalespersonName', 'DealershipLocation', 'Profit'],
      dtype='object')

In [8]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [9]:
# to add new column(Age Group)
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

In [10]:
df.columns

Index(['car_model', 'country', 'city', 'price', 'quantitysold', 'sale',
       'dateofsale', 'customerid', 'customername', 'age', 'gender', 'carmake',
       'carmodel', 'year', 'cartype', 'paymentmethod', 'salespersonid',
       'salespersonname', 'dealershiplocation', 'profit', 'age_group'],
      dtype='object')

In [16]:
from sqlalchemy import create_engine

# MySQL connection
username = "root"
password = "2121"
host = "localhost"
port = "3306"
database = "carsale"

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

# Write DataFrame to MySQL
table_name = "cars"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

# Read back sample
pd.read_sql("SELECT * FROM cars LIMIT 5;", engine)

,car_model,country,city,price,quantitysold,sale,dateofsale,customerid,customername,age,...,carmake,carmodel,year,cartype,paymentmethod,salespersonid,salespersonname,dealershiplocation,profit,age_group
0,Hyundai Elantra,USA,Phoenix,58969,9,530721,2024-10-19,CUST00001,David Newton,24,...,Mercedes,Mercedes C-Class,2022,SUV,Cash,SP050,Daisy Becker,"Lisaside, Palestinian Territory",7504,Young Adult
1,Honda Civic,Australia,Melbourne,82809,2,165618,2024-10-20,CUST00002,Mark Haas,25,...,Nissan,Ford Focus,2019,Convertible,Credit Card,SP027,Kelly Smith,"South Amber, Reunion",14973,Young Adult
2,Hyundai Elantra,Australia,Adelaide,54925,10,549250,2024-10-21,CUST00003,Emily Brooks,33,...,Toyota,Kia Optima,2007,Truck,Lease,SP071,Christian Morgan,"Kristinmouth, Cuba",7008,Adult
3,BMW 3 Series,Canada,Toronto,34601,10,346010,2024-10-22,CUST00004,Samantha Fernandez,21,...,Toyota,Mercedes C-Class,2016,SUV,Credit Card,SP055,George Santiago,"Patrickmouth, French Guiana",11729,Young Adult
4,BMW 3 Series,France,Nice,49742,1,49742,2024-10-23,CUST00005,Linda Wilson,42,...,BMW,BMW 3 Series,2002,Minivan,Bank Transfer,SP007,Brittany Brown,"Reneeborough, Kyrgyz Republic",6025,Adult

In [12]:
df[['age','age_group']].head(10)

   age    age_group
0   24  Young Adult
1   25  Young Adult
2   33        Adult
3   21  Young Adult
4   42        Adult
5   75       Senior
6   42        Adult
7   58  Middle-aged
8   68       Senior
9   63       Senior

In [15]:
df.dtypes

car_model                     object
country                       object
city                          object
price                          int64
quantitysold                   int64
sale                           int64
dateofsale            datetime64[ns]
customerid                    object
customername                  object
age                            int64
gender                        object
carmake                       object
carmodel                      object
year                           int64
cartype                       object
paymentmethod                 object
salespersonid                 object
salespersonname               object
dealershiplocation            object
profit                         int64
age_group                   category
dtype: object

In [14]:
df['dateofsale'] = pd.to_datetime(df['dateofsale']).dt.normalize()